# -*- coding: utf-8 -*-
"""AI&Data-Day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S_uaH5c-_3tERQW89yxknm9Ugd-T3oiX
"""

playlist=["shape of you","naa ready","beliver"]
fav_foods=["biryani","friedrice","pizza","burger"]
recent_locations=["chennai","hyderabad","banglore"]
print(playlist)
playlist.append("perfect")
playlist.insert(2,"lover")
print(playlist)
playlist.remove("beliver")
print(playlist)
playlist.pop()
print(playlist)

nums=[10,20,30,90,100,40,80,50,70,60,100]
nums.sort()
print(nums)
nums.reverse()
print(nums)
print(nums.count(100))
print(nums[1])
nums[1]=10
print(nums[1])

nums=[10,20,30,90,100,40,80,50,70,60,100]
print(nums[0:3])
print(nums[-2:])

for n in nums:
  print(n)

playlist=["shape of you","naa ready","beliver","faded"]
if "faded" in playlist:
  print("faded is present in the list")
playlist[1]="lover"
print(playlist)

order=["pizza",2,500.00,True]
print(order)
for index, item in enumerate(order):
  print(f"Index: {index}, Item: {item}")

trip=("uber","chennai","hyderabad",3500.50,"completed")
print(trip)
print(trip[2])
print()
for i in trip:
  print(i)
print(len(trip))

trip={"provider":"uber","status":"completed","source":"chennai","destination":"hyderabad","fare":3500.50}
print(trip["provider"])
print(trip.get(3500.50))
print(trip.keys())
print(trip.values())
for key,value in trip.items():
  print(f"Key: {key}, Value: {value}")
trip.update({"Distance":150})
print(trip)
trip.pop("Distance")
print(trip)
trip["fare"]=4000.00
print(trip)
for key in trip:
  print(key,"->",trip[key])
#no duplicate keys but values can be duplicated

myset={1,3,4,5,5,2}
print(myset)
cities={"chennai","hyderabad","mumbai","pune"}
print(cities)
cities.add("goa")
print(cities)
list_cities=list(cities)
print(type(list_cities))
cities2={"hyderabad","delhi","mumbai"}
print(cities.union(cities2))
print(cities.intersection(cities2))
print(cities.difference(cities2))
cities.add("pune")
print(cities)
cities.remove("pune")
print(cities)

add=lambda a,b: a+b
print(add(2,3))
numbers=[1,2,3,4,5,6,7,8,9,10]
even=list(filter(lambda x: x%2==0,numbers))
print(even)
data=[
    {"name":"john","age":25},
    {"name":"jane","age":30},
]
youngest=min(data,key=lambda x: x["age"])
print(youngest)